name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - name: log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:18.9.0-alpine3.16
        with:
          entrypoint: "/bin/echo"
          args: "Hello World"
      - name: Log node version
        uses: docker://node:18.9.0-alpine3.16
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v1
      - name: Run a script
        uses: docker://node:18.9.0-alpine3.16
        with:
          entrypoint: ./script.sh
          args: "Some String"
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: 'curl -X POST http://localhost:3001/api/users -H ''Content-Type: application/json'' -d ''{"username": "hey","address": "dude"}'''
      - name: Get Users
        run: curl http://localhost:3001/api/users
